apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: adhig93/k8snodejs:version_0
        name: nodejs
        ports:
        - containerPort: 3080
      imagePullSecrets:
      - name: dockerhub

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  ports:
  - port: 3080
    targetPort: 3080
    nodePort: 31200
  selector:
    app: webapp
  type: NodePort